all: mqtt-demo

# PROJECT_SOURCEFILES += module.cpp
MODULES += os/net/app-layer/mqtt

CONTIKI = ../..
#CFLAGS	+= -Wno-nonnull-compare -Wno-implicit-function-declaration

include $(CONTIKI)/Makefile.include
